In [1]:
import numpy as np

In [2]:
matriks = np.array([[1, 2, 3], [4, 5, 6], [7, 8 ,9]])
print(matriks)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
matriks = matriks . 2
print(matriks)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [6]:
# Perbandingan ukuran memori matrix python dengan matrix numpy
import sys

try:
    var_list= [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
    var_array= np.array([[1, 2, 3], [4, 5, 6], [7, 8 ,9]])

    print("Ukuran keseluruhan elemen list dalam bytes = ",sys.getsizeof(var_list)*len(var_list))
    print("Ukuran keseluruhan elemen NumPy dalam bytes = ", var_array.size*var_array.itemsize)
except NameError:
    print("Ada variabel yang belum didefinisikan")

Ukuran keseluruhan elemen list dalam bytes =  240
Ukuran keseluruhan elemen NumPy dalam bytes =  72
